backend/src/app.js

Feat: backend 수정 #1

---

backend/src/app.js

커밋 컨벤션, PR 템플릿 사용 연습을 해보던 중 실수로 PR을 진행해버려서 내용을 다시 복구하였습니다ㅠ 변경된 내용은 없습니다.
>

Chore: backend 복구 #1

---

frontend/src/app/login/layout.jsx
frontend/src/app/login/page.jsx
frontend/src/components/common/title.jsx
frontend/src/components/layouts/user-layout.jsx
frontend/src/styles/common/big-button.module.css
frontend/src/styles/common/title.module.css
frontend/src/styles/layouts/user-layout.module.css
frontend/src/styles/pages/login.module.css

로그인 페이지를 만들었습니다.
현재 백엔드가 없는 관계로 로그인 버튼 클릭 시 alert가 나오게 됩니다.
`src/app/login/layout.jsx` 에는 HTML Title 변경과 UserLayout 적용, `src/app/login/page.jsx` 에는 입력 박스, 로그인 버튼 등이 추가되어 있습니다.
UserLayout에서 `flex` 등을 사용해 구현하였습니다.
FHD 환경에서 아래와 같은 UI가 나오게 됩니다.
>
더 나은 방식, 궁금한 점 있으시면 편하게 말씀해주세요!

Feat: 로그인 페이지 추가

---

backend/package.json
backend/src/app.js
backend/src/controller/NotificationController.js
backend/src/controller/ScheduleController.js
backend/src/controller/TeamController.js
backend/src/controller/TeamMemberController.js
backend/src/controller/UserController.js
backend/src/mariadb.js
backend/src/routes/notifications.js
backend/src/routes/schedules.js
backend/src/routes/team_members.js
backend/src/routes/teams.js
backend/src/routes/users.js
package-lock.json

backend 폴더의 구조를 구현하였습니다.
Controller, routes, app.js 구조로 구현했고, 각 컨트롤러와 라우터 아래에 광욱님이 설계해주신 테이블을 토대로 파일명을 생성하였습니다. 
구현 시 필요한 기본 모듈을 설치했고 태훈님이 말씀해주신 내용을 토대로 mariadb.js의 내용은 작성하지 않는 것으로 수정하였으며 .env 파일은 업로드하지 않았습니다. 별도로 작성 후 실행해주시면 될 것 같습니다.
추가적으로 수정하거나 삭제할 내용이 있으면 말씀해주세요!
>

Chore: backend 폴더 구조 구현

---

frontend/src/app/find/layout.jsx
frontend/src/app/login/layout.jsx
frontend/src/app/register/layout.jsx

- `/login`
- `로그인 | Schedule Manager`
- `/register`
- `회원가입 | Schedule Manager`
- `/find`
- `찾기 | Schedule Manager`
로 수정하였습니다.
>

Fix: title 한글로 수정

---

frontend/src/app/login/page.jsx

로그인 페이지 링크 모음과 로그인 버튼 사이 `<br />` 를 추가하였습니다.
>

Fix: 유저 UI 일관성 있게 수정

---

table.sql

table.sql에 알림(notifications) 테이블을 추가했습니다.
>

ADD: SQL 알림 테이블 추가

---

backend/src/controller/UserController.js
backend/src/routes/users.js

User에 대한 백엔드 코드 구조를 구현하였습니다.(users.js, UserController)
만들어주신 User UI를 참고하여 회원가입, 로그인, 아이디 확인, 비밀번호 변경 4가지 기능을 구현하고자 틀을 작성하였습니다.
>

Feat: user.js, UserController 틀 구현

---

frontend/package.json
frontend/src/app/calendar/page.jsx
package-lock.json

`react-big-calendar`, `@toast-ui/calendar` 가 작동을 하지 않는 관계로 `FullCalender` 를 사용하여 화면을 구현하였습니다.
헤더 구현과 클릭 이벤트 감지 등의 작업이 추가로 필요합니다.
>

Feat: FullCalender 사용해 캘린더 구현

---

frontend/package.json
frontend/src/app/calendar/page.jsx
package-lock.json

`@fullcalendar/interaction` 플러그인을 통해 일정별 클릭이 아닌 일별 클릭으로 수정하였습니다.
10월 9일 클릭 시 `/calendar/2024-10-09` 로 리다이렉트 됩니다.
`Date` 오브젝트로도 받을 수 있어서 안되면 format 교체하면 될 것 같습니다
>

Feat: 날짜 클릭 이벤트 핸들링

---

frontend/package.json
frontend/src/app/calendar/layout.jsx
frontend/src/app/calendar/page.jsx
frontend/src/components/calendar/header.jsx
frontend/src/styles/calendar/header.module.css
package-lock.json

캘린더에서 사용할 헤더를 구현하였습니다.
아직 버튼 click은 구현하지 않았습니다.
>

Feat: 헤더 구현

---

frontend/package.json
frontend/src/app/find/changePassword/page.jsx
frontend/src/app/find/page.jsx
frontend/src/app/login/page.jsx
frontend/src/app/register/page.jsx
frontend/src/components/common/input-box.jsx
frontend/src/styles/layouts/user-layout.module.css
frontend/src/styles/pages/login.module.css
package-lock.json

로그인, 회원가입, 비밀번호 변경 등의 기능을 `react-hook-form` 를 사용해 `form` 으로 교체하였습니다.
비밀번호 두번 입력 validate도 가능했지만 당장 구현할 필요가 없다고 판단해 `onSubmit` 함수 에서 처리하도록 했습니다.
>

Feat: react-hook-form 사용

---

frontend/src/app/calendar/[id]/page.jsx
frontend/src/components/common/schedule-input-box.jsx
frontend/src/styles/common/schedule-input-box.module.css
frontend/src/styles/pages/id.module.css

- [✔️] ScheduleInputBox 컴포넌트 구현
- [✔️] 캘린더 상세 페이지(일정 추가, 수정, 삭제) 구현
- [✔️] 캘린더 상세 페이지 날짜 불러오기
- 캘린더 상세 페이지(조회)
- 캘린더 상세 페이지(수정)
- 캘린더 상세 페이지(삭제)
- 캘린더 상세 페이지(추가)
- events 배열과 id 값을 setState 로 관리하도록 했습니다. 괜찮은지 확인 부탁드립니다.

Feat: 캘린더 상세 페이지 구현

---

backend/package.json
backend/src/controller/NotificationController.js
backend/src/routes/notifications.js
package-lock.json
package.json

알람 기능을 구현하였습니다.
해당 기능에 필요한 node-cron, moment-timezone 모듈을 설치하였습니다.
>

Feat: 알림 기능 구현

---

frontend/package.json
frontend/src/app/page.jsx
frontend/src/components/common/loading-spinner.jsx
frontend/src/data/use-user.js
frontend/src/libs/api-fetcher.js
frontend/src/libs/jwt.js
frontend/src/styles/common/loading-spinner.module.css
package-lock.json

swr 라이브러리를 사용하였습니다.
`/` 페이지에서 백엔드에 요청해 로그인 된 유저인지 확인하기 위해 작업하였으나 백엔드에 관련 API가 없는 관계로 jwt 토큰을 체크하는 방식으로 변경하였습니다.
>

Feat: SWR 라이브러리 사용

---

backend/src/controller/ScheduleController.js
backend/src/routes/schedules.js

> 일정 업데이트 기능을 추가했습니다.
> start_date, end_date, start_time, end_time 부분적으로 수정 가능하게 구현했습니다.
>

일정 업데이트 기능 추가

---

backend/package.json
backend/src/app.js
package-lock.json

백엔드와 프론트엔드간 통신을 위해 CORS 설정을 진행하였습니다.
>

Feat: 프론트 통신을 위한 cors 세팅

---

frontend/src/app/login/page.jsx

`fetch` 기능을 사용해 로그인 기능을 구현하였습니다.
#28 PR이 merge 되어야 정상 작동합니다.
>

Feat: 로그인 페이지 로직 구현

---

frontend/src/app/register/page.jsx

회원가입 페이지 로직을 구현하였습니다.
백엔드에서 400에러를 보내며 이메일 validate를 하지만 db 쿼리 실패시에도 400 에러를 보내는 관계로 validate 메시지 alert 기능은 구현하지 않았습니다.
>

Feat: 회원가입 페이지 로직 구현

---

backend/src/controller/UserController.js

토큰 쿠키 발급 시 보안 상의 이유로 HttpOnly를 포함했지만 요구하셔서 제거하였습니다.
>

Fix: 토큰 발급 시 HTTPOnly 삭제

---

backend/src/controller/NotificationController.js
backend/src/email.js

알람 전송 실행 시 알람이 전송되지 않는 오류를 수정했습니다.
그리고 스케줄러 동작 함수를 콘솔창에서 진행 사항을 알 수 있게 일부 수정하였고, 서버 시간을 Asia/Seoul로 맞추었습니다.
>

Fix: 알람 전송 수정

---

backend/src/controller/ScheduleController.js
backend/src/routes/schedules.js

일정 공유 기능 추가

---

backend/src/controller/ScheduleController.js
table.sql

SQL 테이블 변경
(1) user_email -> user_id
(2) detail 삭제
notification.js 구조 일부 변경
>

Fix: SQL 수정 및 알람 구조 변경

---

frontend/src/app/find/page.jsx

아이디 찾기 페이지 로직을 구현하였습니다.
이메일 넘기는건 세션 스토리지로 해결하였습니다.
>

Feat: 아이디 찾기 로직 구현

---

frontend/src/components/calendar/header.jsx

헤더에 Link를 추가하였습니다.
알람 링크는 어떻게 될지 몰라 임의로 `/alert`로 지정해두었습니다.
>

Feat: 헤더 Link 추가

---

frontend/src/app/find/changePassword/page.jsx

비밀번호 변경 페이지 로직을 구현하였습니다.
비밀번호를 제대로 입력하였는지 확인합니다.
이메일 정보는 JWT 토큰이 존재하면 JWT 토큰에서, 존재하지 않으면 sessionStorage에서 가져오는 방식으로 해결하였습니다.
>

Feat: 비밀번호 변경 로직 구현

---

frontend/src/app/calendar/new/page.jsx
frontend/src/app/calendar/page.jsx

`/calendar/new` 가 필요하지 않은 상황이라 제거하였습니다.
추가로 `새 일정` 버튼도 같이 제거되었습니다.
>

Remove: /calendar/new 제거

---

backend/package-lock.json
frontend/package-lock.json
table.sql

데이터 베이스 테이블 수정

---

frontend/src/app/calendar/page.jsx
frontend/src/app/page.jsx
frontend/src/data/use-schedule.js
frontend/src/data/use-user.js
frontend/src/libs/url.js

메인 캘린더 페이지의 로직을 구현하였습니다.
데이터가 없는 관계로 테스트 해보지 못하였으며 일정 추가 제거 등의 기능 구현 후 재확인 예정입니다.
>

Feat: 메인 캘린더 로직 구현

---

frontend/src/app/calendar/page.jsx

백엔드 데이터 구조와 FullCalender events 데이터 구조가 다른 관계로 변환을 진행하였습니다.
>

Fix: events에 들어갈 데이터 변환

---

frontend/src/app/calendar/page.jsx
frontend/src/styles/calendar/calendar-overwrite.css

캘린더 상 일, 토 부분의 색을 변경하였습니다.
클릭 가능한 일 필드의 커서를 pointer로 지정하였습니다.
>

Design: 캘린더 디자인 일부 수정

---

backend/src/controller/ScheduleController.js

> 수정된 테이블 비교해서 코드 수정했고, 테스트했습니다.
>

일정 관련 API 테스트 후 수정

---

backend/src/controller/NotificationController.js
backend/src/controller/UserController.js

명세서 작성 중 response 형식이 results로 선언한 게 많아 복잡할 것 같아서 조회 기능 제외하고 나머지 모두 메시지 형식으로 변경하였습니다.
>

Fix: 유저 및 알람 res 수정

---

API.md

유저와 알람에 대한 API 명세서를 작성하였습니다.
수정할 부분이 있으시면 말씀해 주세요!
>

Add: API 명세서 작성(User, Notification)

---

API.md

API 명세서에 알람 수정이 누락되어 추가하였습니다.
>

Add: 알람 수정 추가
